all: help

help:
	@echo "Este es el Makefile de la P1 de Alba Ramos y Nicolás Serrano"
	@echo "Los comandos disponibles son:"
	@echo "ayuda_mp, compila_mp, ejecuta_mp, compilar, ayuda_per, ejecuta_per, ayuda_ada, ejecuta_ada"

ayuda_mp:
	python3 main.py -ayuda_mp

compila_mp:
	python3 main.py -compila_mp

ejecuta_mp:
	python3 main.py -ejecuta_mp

compilar:
	python3 main4_1.py -compilar

ayuda_per:
	python3 main4_1.py -ayuda_per

ejecuta_per:
	python3 main4_1.py -ejecuta_per

ayuda_ada:
	python3 main4_1.py -ayuda_ada

ejecuta_ada:
	python3 main4_1.py -ejecuta_ada