;**************************************************************************
; 									SBM 
; Pareja numero: 5
; Alba Ramos Pedroviejo
; Arturo Morcillo Penares
;**************************************************************************

; DEFINICION DEL SEGMENTO DE DATOS 
DATOS SEGMENT 
	CLR_PANT 		DB 	1BH,"[2","J$",'$' 
	
	MENSAJE_ERROR 	DB 	1BH,"[16;1fValor incorrecto. Asegurate de leer bien las instrucciones para la siguiente ;) $"
	
	MENU_TIULO 		DB 	1BH,"[5;1fMATRIX CALCULATOR TM $"
	MENU_AUTOR 		DB 	1BH,"[6;1fAlba Ramos, Arturo Morcillo $"
	MENU_LEGAL 		DB 	1BH,"[7;1fTodos los derechos reservados $"
	MENU_OPCIONES 	DB 	1BH,"[13;1f1.Calcular un determinante por defecto     2.Introducir tus propios valores$"
	MENU_INPUT		DB 	1BH,"[15;1fIntroducir opcion: $"
	MSG_FORMATO1	DB 	1BH,"[13;1fA continuacion se le solicitaran los numeros de la matriz por filas $"
	MSG_FORMATO2	DB 	1BH,"[14;1fLos numeros validos van desde -16 hasta 15, incluidos $"
	MSG_CONTINUAR	DB 	1BH,"[15;1fPara continuar, pulse 1. Para regresar al menu, pulse 2: $"
	
	;FILAS DE LA MATRIZ CON LOS VALORES POR DEFECTO. 10,13 ES UN \n
	FILA1 			DB 	1BH,"      |  2   0   0|",10,13,'$'
	FILA2			DB 	1BH,"|A| = |  5   9   0| =          ",10,13,'$' 
	FILA3 			DB 	1BH,"      | 10   2   3|",10,13,'$' 
	
	AUX				DB 	5 DUP (0) 
	
	TECLADO_A11 	DB 	1BH,"[15;1fESCRIBE A11 : $"
	TECLADO_A12 	DB 	1BH,"[15;1fESCRIBE A12 : $"
	TECLADO_A13 	DB 	1BH,"[15;1fESCRIBE A13 : $"
	TECLADO_A21 	DB 	1BH,"[15;1fESCRIBE A21 : $"
	TECLADO_A22 	DB 	1BH,"[15;1fESCRIBE A22 : $"
	TECLADO_A23 	DB 	1BH,"[15;1fESCRIBE A23 : $"
	TECLADO_A31 	DB 	1BH,"[15;1fESCRIBE A31 : $"
	TECLADO_A32 	DB 	1BH,"[15;1fESCRIBE A32 : $"
	TECLADO_A33 	DB 	1BH,"[15;1fESCRIBE A33 : $"

	MATRIZ  		DW     2,0,0,5,9,0,10,2,3	;MATRIZ CON LOS VALORES DECIMALES POR DEFECTO
	RESULTADOS 		DW 6 dup (0) 				;TABLA QUE ALMACENA LAS MULTIPLICACIONES
DATOS ENDS 


; DEFINICION DEL SEGMENTO DE PILA 
PILA    SEGMENT STACK "STACK" 
    DB   40H DUP (0) 
PILA ENDS 


; DEFINICION DEL SEGMENTO EXTRA
EXTRA     SEGMENT 
    RESULT    DW 0,0  
EXTRA ENDS 


; DEFINICION DEL SEGMENTO DE CODIGO
CODE    SEGMENT 
    ASSUME CS:CODE, DS:DATOS, ES: EXTRA, SS:PILA 

	; COMIENZO DEL PROCEDIMIENTO PRINCIPAL
	START PROC 
		;INICIALIZA LOS REGISTROS DE SEGMENTO CON SUS VALORES 
		MOV AX, DATOS 
		MOV DS, AX 

		MOV AX, PILA 
		MOV SS, AX 

		MOV AX, EXTRA 
		MOV ES, AX 

		; CARGA EL PUNTERO DE PILA CON EL VALOR MAS ALTO 
		MOV SP, 64 

		;COMIENZO DEL PROGRAMA 
	MENU:
		CALL MOSTRAR_MENU
		
		CMP AUX[2],31h 		; HA INTRODUCIDO UN 1, QUIERE EL DET. POR DEFECTO
		JE DEFAULT
		
		CMP AUX[2], 32h		; HA INTRODUCIDO UN 2, QUIERE SUS PROPIOS VALORES
		JE CUSTOM
		
		JMP LANZAR_ERROR    ; HA INTRODUCIDO OTRA COSA, ERROR

		
		;---------------------------------------------
		;-------DETERMINANTE POR DEFECTO -------------
		;---------------------------------------------
		DEFAULT:
			CALL DETERMINANTE
			;AHORA AX Y BX CONTIENEN EL VALOR DEL DETERMINANTE
			CALL GUARDAR_RESULTADO
			JMP IMPRESION_FINAL
			
		;---------------------------------------------
		;-------DETERMINANTE PERSONALIZADO------------
		;---------------------------------------------
		CUSTOM:
			MOV AH,9
			MOV DX, OFFSET CLR_PANT
			INT 21H
			MOV DX,OFFSET MENU_TIULO		
			INT 21H
			MOV DX,OFFSET MENU_AUTOR		
			INT 21H
			MOV DX,OFFSET MENU_LEGAL		
			INT 21H
			MOV DX,OFFSET MSG_FORMATO1		
			INT 21H
			MOV DX,OFFSET MSG_FORMATO2	
			INT 21H
			MOV DX,OFFSET MSG_CONTINUAR	
			INT 21H
			
			MOV AH,0AH			;ALMACENA LA OPCION TECLEADA EN AUX, COMO MAXIMO 1 CARACTER
			MOV DX,OFFSET AUX
			MOV AUX[0],2		
			INT 21H
			
			CMP AUX[2], 31H		; HA INTRODUCIDO UN 1, QUIERE SEGUIR
			JE SEGUIR
			
			CMP AUX[2], 32h		; HA INTRODUCIDO UN 2, QUIERE IR ATRAS
			JE MENU
			
			JMP LANZAR_ERROR	; HA INTRODUCIDO OTRA COSA, ERROR
			
		;-------PRIMERA FILA--------------------------
		;------ALMACENAMOS EL VALOR LEIDO POR TECLADO EN A11
		SEGUIR:
			MOV AH,9
			MOV DX, OFFSET CLR_PANT
			INT 21H
			
			MOV DX,OFFSET TECLADO_A11
			INT 21H
			
			MOV AH,0AH			;ALMACENA EL NUMERO TECLEADO
			MOV DX,OFFSET AUX
			MOV AUX[0],4
			INT 21H
			
			CMP AUX[1],1  		;HA INTRODUCIDO SOLO UN CARACTER
			JE LABEL1
			
			CMP AUX[1], 2 		;HA INTRODUCIDO DOS CARACTERES
			JE LABEL2
			
			JMP CONTINUA1  		;HA INTRODUCIDO 3 CARACTERES
			
		LABEL1:	
			CALL TECLADO1
			JMP CONTINUA1
		LABEL2:	
			CALL TECLADO2
			JMP CONTINUA1
		CONTINUA1:	
			; ALMACENA LOS ASCII
			MOV AL, AUX[2]
			MOV FILA1[8], AL
			MOV AL, AUX[3]
			MOV FILA1[9], AL
			MOV AL, AUX[4]
			MOV FILA1[10], AL
			
			; CONVERTIMOS EL NUMERO ASCII A DECIMAL
			CMP AUX[2], 45 ;EL NUMERO TIENE DOS CIFRAS Y ES NEGATIVO (-XX)
			JE NEGATIVO2
			
			CMP AUX[3], 45 ;EL NUMERO TIENE UNA CIFRA Y ES NEGATIVO (-X)
			JE NEGATIVO1
			
			JMP NORMAL1	   ;RESTO DE CASOS(XXX, XX, X)
			
		NEGATIVO2:
			CALL MENOS2
			JMP CONVERTIDO1
		NEGATIVO1:
			CALL MENOS1
			JMP CONVERTIDO1
		NORMAL1:
			CALL CONVERTIRNUMERO
		
		; EL NUMERO DECIMAL DE BX SE GUARDA
		CONVERTIDO1:
			MOV MATRIZ[0],BX
			
		;------ALMACENAMOS EL VALOR LEIDO POR TECLADO EN A12
			MOV AH,9	
			MOV DX, OFFSET CLR_PANT
			INT 21H
			MOV DX,OFFSET TECLADO_A12		
			INT 21H
			MOV AH,0AH			
			MOV DX,OFFSET AUX
			MOV AUX[0],4		
			INT 21H
			
			CMP AUX[1],1 ;HA INTRODUCIDO UN CARACTER
			JE LABEL3
			
			CMP AUX[1],2 ;HA INTRODUCIDO DOS CARACTERES
			JE LABEL4
			
			JMP CONTINUA2 ;HA INTRODUCIDO 3 CARACTERES
			
		LABEL3:	CALL TECLADO1
			JMP CONTINUA2
		LABEL4:	CALL TECLADO2
			JMP CONTINUA2
		CONTINUA2:
			MOV AL, AUX[2]
			MOV FILA1[12], AL
			MOV AL, AUX[3]
			MOV FILA1[13], AL
			MOV AL, AUX[4]
			MOV FILA1[14], AL
			
			CMP AUX[2], 45 ; EL NUMERO TIENE DOS CIFRAS Y ES NEGATIVO
			JE NEGATIVO22
			
			CMP AUX[3], 45 ; EL NUMERO TIENE UNA CIFRA Y ES NEGATIVO
			JE NEGATIVO12
			
			JMP NORMAL2
			
		NEGATIVO22:
			CALL MENOS2
			JMP CONVERTIDO2
		NEGATIVO12:
			CALL MENOS1
			JMP CONVERTIDO2
		NORMAL2:
			CALL CONVERTIRNUMERO
			
		CONVERTIDO2:
			MOV MATRIZ[1*2],BX
			
		;-----ALMACENAMOS EL VALOR LEIDO POR TECLADO EN A11-----
			MOV AH,9	
			MOV DX, OFFSET CLR_PANT
			INT 21H
			MOV DX,OFFSET TECLADO_A13		
			INT 21H
			MOV AH,0AH			
			MOV DX,OFFSET AUX
			MOV AUX[0],4		
			INT 21H
			
			CMP AUX[1],1 ;HA INTRODUCIDO SOLO UN CARACTER
			JE LABEL5
			
			CMP AUX[1],2 ;HA INTRODUCIDO SOLO DOS CARACTERES
			JE LABEL6
			
			JMP CONTINUA3 ;HA INTRODUCIDO 3 CARACTERES
			
		LABEL5:	CALL TECLADO1
			JMP CONTINUA3
		LABEL6:	CALL TECLADO2
			JMP CONTINUA3
			
		CONTINUA3:
			MOV AL, AUX[2]
			MOV FILA1[16], AL
			MOV AL, AUX[3]
			MOV FILA1[17], AL
			MOV AL, AUX[4]
			MOV FILA1[18], AL
			
			CMP AUX[2], 45 ; EL NUMERO TIENE DOS CIFRAS Y ES NEGATIVO
			JE NEGATIVO23
			
			CMP AUX[3], 45 ; EL NUMERO TIENE UNA CIFRA Y ES NEGATIVO
			JE NEGATIVO13
			
			JMP NORMAL3
			
		NEGATIVO23:
			CALL MENOS2
			JMP CONVERTIDO3
		NEGATIVO13:
			CALL MENOS1
			JMP CONVERTIDO3
		NORMAL3:
			CALL CONVERTIRNUMERO
			
		CONVERTIDO3:	
			MOV MATRIZ[2*2],BX
			
		;-------SEGUNDA FILA--------------------------
			
		;----ALMACENAMOS EL VALOR LEIDO POR TECLADO EN A21----
			MOV AH,9	; BORRA LA PANTALLA
			MOV DX, OFFSET CLR_PANT
			INT 21H
			MOV DX,OFFSET TECLADO_A21		
			INT 21H
			MOV AH,0AH			
			MOV DX,OFFSET AUX
			MOV AUX[0],4		
			INT 21H
			
			CMP AUX[1],1 ;HA INTRODUCIDO SOLO UN CARACTER
			JE LABEL7
			
			CMP AUX[1],2 ;HA INTRODUCIDO SOLO DOS CARACTERES
			JE LABEL8
			
			JMP CONTINUA4 ;HA INTRODUCIDO 3 CARACTERES
			
		LABEL7:	CALL TECLADO1
			JMP CONTINUA4
		LABEL8:	CALL TECLADO2
			JMP CONTINUA4
		CONTINUA4:
			MOV AL, AUX[2]
			MOV FILA2[8], AL
			MOV AL, AUX[3]
			MOV FILA2[9], AL
			MOV AL, AUX[4]
			MOV FILA2[10], AL
			
			CMP AUX[2], 45 ;SI EL NUMERO TIENE DOS CIFRAS Y ES NEGATIVO
			JE NEGATIVO24
			
			CMP AUX[3], 45 ;SI EL NUMERO TIENE UNA CIFRA Y ES NEGATIVO
			JE NEGATIVO14
			
			JMP NORMAL4
			
		NEGATIVO24:
			CALL MENOS2
			JMP CONVERTIDO4
		NEGATIVO14:
			CALL MENOS1
			JMP CONVERTIDO4
		NORMAL4:
			CALL CONVERTIRNUMERO
		CONVERTIDO4:
			MOV MATRIZ[3*2],BX
			
		;-----ALMACENAMOS EL VALOR LEIDO POR TECLADO EN A22-----
			MOV AH,9	
			MOV DX, OFFSET CLR_PANT
			INT 21H
			MOV DX,OFFSET TECLADO_A22		
			INT 21H
			MOV AH,0AH			
			MOV DX,OFFSET AUX
			MOV AUX[0],4		
			INT 21H
			
			CMP AUX[1],1 ;HA INTRODUCIDO SOLO UN CARACTER
			JE LABEL9
			CMP AUX[1],2 ;HA INTRODUCIDO SOLO DOS CARACTERES
			JE LABEL10
			JMP CONTINUA5 ;HA INTRODUCIDO 3 CARACTERES
			
		LABEL9:	
			CALL TECLADO1
			JMP CONTINUA5
		LABEL10:	
			CALL TECLADO2
			JMP CONTINUA5
		CONTINUA5:
			MOV AL, AUX[2]
			MOV FILA2[12], AL
			MOV AL, AUX[3]
			MOV FILA2[13], AL
			MOV AL, AUX[4]
			MOV FILA2[14], AL
			
			CMP AUX[2], 45 ;SI EL NUMERO TIENE DOS CIFRAS Y ES NEGATIVO
			JE NEGATIVO25
			CMP AUX[3], 45 ;SI EL NUMERO TIENE UNA CIFRA Y ES NEGATIVO
			JE NEGATIVO15
			JMP NORMAL5
			
		NEGATIVO25:
			CALL MENOS2
			JMP CONVERTIDO5
		NEGATIVO15:
			CALL MENOS1
			JMP CONVERTIDO5
		NORMAL5:
			CALL CONVERTIRNUMERO
		CONVERTIDO5:
			MOV MATRIZ[4*2],BX
			
		;-----ALMACENAMOS EL VALOR LEIDO POR TECLADO EN A23-----
			MOV AH,9	
			MOV DX, OFFSET CLR_PANT
			INT 21H
			MOV DX,OFFSET TECLADO_A23		
			INT 21H
			MOV AH,0AH			
			MOV DX,OFFSET AUX
			MOV AUX[0],4		
			INT 21H
			
			CMP AUX[1],1 ;HA INTRODUCIDO SOLO UN CARACTER
			JE LABEL11
			CMP AUX[1],2 ;HA INTRODUCIDO SOLO DOS CARACTERES
			JE LABEL12
			JMP CONTINUA6 ;HA INTRODUCIDO 3 CARACTERES
			
		LABEL11:	
			CALL TECLADO1
			JMP CONTINUA6
		LABEL12:	
			CALL TECLADO2
			JMP CONTINUA6
		CONTINUA6:
			MOV AL, AUX[2]
			MOV FILA2[16], AL
			MOV AL, AUX[3]
			MOV FILA2[17], AL
			MOV AL, AUX[4]
			MOV FILA2[18], AL
			
			CMP AUX[2], 45 ;SI EL NUMERO TIENE DOS CIFRAS Y ES NEGATIVO
			JE NEGATIVO26
			CMP AUX[3], 45 ;SI EL NUMERO TIENE UNA CIFRA Y ES NEGATIVO
			JE NEGATIVO16
			JMP NORMAL6
			
		NEGATIVO26:
			CALL MENOS2
			JMP CONVERTIDO6
		NEGATIVO16:
			CALL MENOS1
			JMP CONVERTIDO6
		NORMAL6:
			CALL CONVERTIRNUMERO
		CONVERTIDO6:
			MOV MATRIZ[5*2],BX
			
		;---------------------------------------------
		;-------TERCERA FILA--------------------------
		;---------------------------------------------
		;---ALMACENAMOS EL VALOR LEIDO POR TECLADO EN A31---
			MOV AH,9	
			MOV DX, OFFSET CLR_PANT
			INT 21H
			MOV DX,OFFSET TECLADO_A31		
			INT 21H
			MOV AH,0AH			
			MOV DX,OFFSET AUX
			MOV AUX[0],4		
			INT 21H
			
			CMP AUX[1],1 ;HA INTRODUCIDO SOLO UN CARACTER
			JE LABEL13
			CMP AUX[1],2 ;HA INTRODUCIDO SOLO DOS CARACTERES
			JE LABEL14
			JMP CONTINUA7 ;HA INTRODUCIDO 3 CARACTERES
			
			
		LABEL13:	
			CALL TECLADO1
			JMP CONTINUA7
		LABEL14:	
			CALL TECLADO2
			JMP CONTINUA7
		CONTINUA7:
			MOV AL, AUX[2]
			MOV FILA3[8], AL
			MOV AL, AUX[3]
			MOV FILA3[9], AL
			MOV AL, AUX[4]
			MOV FILA3[10], AL
			
			CMP AUX[2], 45 ;SI EL NUMERO TIENE DOS CIFRAS Y ES NEGATIVO
			JE NEGATIVO27
			CMP AUX[3], 45 ;SI EL NUMERO TIENE UNA CIFRA Y ES NEGATIVO
			JE NEGATIVO17
			JMP NORMAL7
			
		NEGATIVO27:
			CALL MENOS2
			JMP CONVERTIDO7
		NEGATIVO17:
			CALL MENOS1
			JMP CONVERTIDO7
		NORMAL7:
			CALL CONVERTIRNUMERO
		CONVERTIDO7:
			MOV MATRIZ[6*2],BX	
			
		;-----ALMACENAMOS EL VALOR LEIDO POR TECLADO EN A32-----
			MOV AH,9	
			MOV DX, OFFSET CLR_PANT
			INT 21H
			MOV DX,OFFSET TECLADO_A32		
			INT 21H
			MOV AH,0AH			
			MOV DX,OFFSET AUX
			MOV AUX[0],4		
			INT 21H
			
			CMP AUX[1],1 ;HA INTRODUCIDO SOLO UN CARACTER
			JE LABEL15
			CMP AUX[1],2 ;HA INTRODUCIDO SOLO DOS CARACTERES
			JE LABEL16
			JMP CONTINUA8 ;HA INTRODUCIDO 3 CARACTERES
			
		LABEL15:	
			CALL TECLADO1
			JMP CONTINUA8
		LABEL16:	
			CALL TECLADO2
			JMP CONTINUA8
		CONTINUA8:
			MOV AL, AUX[2]
			MOV FILA3[12], AL
			MOV AL, AUX[3]
			MOV FILA3[13], AL
			MOV AL, AUX[4]
			MOV FILA3[14], AL
			
			CMP AUX[2], 45 ;SI EL NUMERO TIENE DOS CIFRAS Y ES NEGATIVO
			JE NEGATIVO28
			CMP AUX[3], 45 ;SI EL NUMERO TIENE UNA CIFRA Y ES NEGATIVO
			JE NEGATIVO18
			JMP NORMAL8
			
		NEGATIVO28:
			CALL MENOS2
			JMP CONVERTIDO8
		NEGATIVO18:
			CALL MENOS1
			JMP CONVERTIDO8
		NORMAL8:
			CALL CONVERTIRNUMERO
		CONVERTIDO8:
			MOV MATRIZ[7*2],BX
			
		;-----ALMACENAMOS EL VALOR LEIDO POR TECLADO EN A33-----
			MOV AH,9	
			MOV DX, OFFSET CLR_PANT
			INT 21H
			MOV DX,OFFSET TECLADO_A33		
			INT 21H
			MOV AH,0AH			
			MOV DX,OFFSET AUX
			MOV AUX[0],4		
			INT 21H
			
			CMP AUX[1],1 ;HA INTRODUCIDO SOLO UN CARACTER
			JE LABEL17
			CMP AUX[1],2 ;HA INTRODUCIDO SOLO DOS CARACTERES
			JE LABEL18
			JMP CONTINUA9 ;HA INTRODUCIDO 3 CARACTERES
			
		LABEL17:	
			CALL TECLADO1
			JMP CONTINUA9
		LABEL18:	
			CALL TECLADO2
			JMP CONTINUA9
		CONTINUA9:
			MOV AL, AUX[2]
			MOV FILA3[16], AL
			MOV AL, AUX[3]
			MOV FILA3[17], AL
			MOV AL, AUX[4]
			MOV FILA3[18], AL
			
			CMP AUX[2], 45 ;SI EL NUMERO TIENE DOS CIFRAS Y ES NEGATIVO
			JE NEGATIVO29
			CMP AUX[3], 45 ;SI EL NUMERO TIENE UNA CIFRA Y ES NEGATIVO
			JE NEGATIVO19
			JMP NORMAL9
			
		NEGATIVO29:
			CALL MENOS2
			JMP CONVERTIDO9
		NEGATIVO19:
			CALL MENOS1
			JMP CONVERTIDO9
		NORMAL9:
			CALL CONVERTIRNUMERO
		CONVERTIDO9:
			MOV MATRIZ[8*2],BX
		
		;-------------------------------------------------------------------
		;---------------------CALCULO DEL DETERMINANTE----------------------
		;-------------------------------------------------------------------
			CALL DETERMINANTE
			
			;AHORA AX Y BX CONTIENEN EL VALOR DEL DETERMINANTE. COMPROBAMOS SI EL RESULTADO ES NEGATIVO O NO
			test BX, BX
			JS NEGATIVO
			JMP POSITIVO
			
		NEGATIVO:
			CALL GUARDAR_RESULTADO_NEGATIVO
			JMP IMPRESION_FINAL
		POSITIVO: 
			CALL GUARDAR_RESULTADO

		IMPRESION_FINAL:
			MOV AH,9	
			MOV DX, OFFSET CLR_PANT
			INT 21H
			MOV DX,OFFSET FILA1		
			INT 21H
			MOV DX,OFFSET FILA2		
			INT 21H
			MOV DX,OFFSET FILA3		
			INT 21H
			
			; FIN DEL PROGRAMA 
			MOV AX, 4C00H 
			INT 21H

		LANZAR_ERROR:
			CALL INPUT_ERROR
	START ENDP 

	;__________________________________________________________________________________
	; SUBRUTINA QUE LANZA UN MENSAJE DE ERROR CUANDO SE INTRODUCE UNA OPCION INCORRECTA
	; IMPLICA LA TERMINACION DEL PROGRAMA
	; NO DEVUELVE NADA
	;__________________________________________________________________________________
	INPUT_ERROR PROC NEAR
		MOV AH,9
		MOV DX, OFFSET CLR_PANT
		INT 21H
		MOV DX,OFFSET MENU_TIULO		
		INT 21H
		MOV DX,OFFSET MENU_AUTOR		
		INT 21H
		MOV DX,OFFSET MENU_LEGAL		
		INT 21H
		MOV DX,OFFSET MENSAJE_ERROR		
		INT 21H
		; FIN DEL PROGRAMA 
		MOV AX, 4C00H 
		INT 21H
	INPUT_ERROR ENDP
	
	;_______________________________________________________________ 
	; SUBRUTINA PARA MOSTRAR EL MENU PRINCIPAL
	; NO DEVUELVE NADA
	;_______________________________________________________________ 
	MOSTRAR_MENU PROC NEAR
		MOV AH,9
		MOV DX, OFFSET CLR_PANT
		INT 21H
		MOV DX,OFFSET MENU_TIULO		
		INT 21H
		MOV DX,OFFSET MENU_AUTOR		
		INT 21H
		MOV DX,OFFSET MENU_LEGAL		
		INT 21H
		MOV DX,OFFSET MENU_OPCIONES		
		INT 21H
		MOV DX,OFFSET MENU_INPUT	
		INT 21H
		
		MOV AH,0AH			;ALMACENA LA OPCION TECLEADA EN AUX, COMO MAXIMO 1 CARACTER
		MOV DX,OFFSET AUX
		MOV AUX[0],2		
		INT 21H
	MOSTRAR_MENU ENDP

	;_______________________________________________________________ 
	; SUBRUTINA PARA GUARDAR EL RESULTADO DEL DETERMINANTE EN LA
    ; FILA 2 PARA MOSTRARLO EN ASCII
	; RECIBE BX CON EL VALOR DEL DETERMINANTE
	; DEVUELVE AX CON EL VALOR DEL DESPLAZAMIENTO Y DX CON EL VALOR DEL SEGMENTO
	;_______________________________________________________________ 
	GUARDAR_RESULTADO PROC NEAR
		MOV AX, BX ;AHORA AX CONTIENE EL VALOR DEL DETERMINANTE PARA REALIZAR LAS OPERACIONES PERTINENTES
		MOV DX,0
		MOV CX, 1000
		DIV CX
		ADD AL,48
		MOV FILA2[24],AL
		
		MOV AX, DX 
		MOV DX,0
		MOV CX, 100
		DIV CX
		ADD AL,48
		MOV FILA2[25],AL
		
		MOV AX,DX
		MOV BL, 10
		DIV BL
		ADD AL, 48
		MOV FILA2[26],AL
		
		MOV AL,AH
		ADD AL, 48
		MOV FILA2[27],AL
		;AHORA EN FILA2 ESTA ESCRITO EL RESULTADO
		MOV AX, 23
		MOV DX, SEG FILA2
		RET
	GUARDAR_RESULTADO ENDP
	
	;_______________________________________________________________ 
	; SUBRUTINA PARA GUARDAR EL RESULTADO DEL DETERMINANTE EN LA
    ; FILA 2 PARA MOSTRARLO EN ASCII, CUANDO EL VALOR DEL DETERMINANTE ES NEGATIVO
	; RECIBE BX CON EL VALOR DEL DETERMINANTE
	; DEVUELVE AX CON EL VALOR DEL DESPLAZAMIENTO Y DX CON EL VALOR DEL SEGMENTO
	;_______________________________________________________________ 
	GUARDAR_RESULTADO_NEGATIVO PROC NEAR
		MOV AL, 45	;MOSTRAR EL SIGNO '-'
		MOV FILA2[23],AL
		
		MOV AX, BX ;AHORA AX CONTIENE EL VALOR DEL DETERMINANTE PARA REALIZAR LAS OPERACIONES PERTINENTES
		NOT AX
		INC AX
		MOV DX,0
		MOV CX, 1000
		DIV CX
		ADD AL,48
		MOV FILA2[24],AL
		
		MOV AX, DX 
		MOV DX,0
		MOV CX, 100
		DIV CX
		ADD AL,48
		MOV FILA2[25],AL
		
		MOV AX,DX
		MOV BL, 10
		DIV BL
		ADD AL, 48
		MOV FILA2[26],AL

		MOV AL,AH
		ADD AL, 48
		MOV FILA2[27],AL
		;AHORA EN FILA2 ESTA ESCRITO EL RESULTADO
		MOV AX, 23
		MOV DX, SEG FILA2
		RET
	GUARDAR_RESULTADO_NEGATIVO ENDP

	;_______________________________________________________________ 
	; SUBRUTINA PARA CALCULAR EL DETERMINANTE DE UNA MATRIZ 
	; SALIDA BX=DETERMINANTE
	;_______________________________________________________________ 
	DETERMINANTE PROC NEAR 
		MOV AX, 0
		;NOTA: PARA ACCEDER A LAS FILAS HAY QUE MULTIPLICAR EL VALOR AL QUE QUEREMOS ACCEDER POR 3
		;PRIMERA MULTIPLICACION QUE SUMA
		MOV AX, MATRIZ[0]
		MOV DX, MATRIZ[4*2]
		IMUL DX                    	;AX = m[0,0] * m[1,1]
		MOV DX, MATRIZ[8*2]	
		IMUL DX 					;AX = m[0,0] * m[1,1] * m[2,2]
		
		MOV RESULTADOS[0], AX
		
		;SEGUNDA MULTIPLICACION QUE SUMA
		MOV AX, MATRIZ[1*2]
		MOV DX, MATRIZ[5*2]
		IMUL DX                    	;AX = m[0,1] * m[1,2]
		MOV DX, MATRIZ[6*2]
		IMUL DX 					;AX = m[0,1] * m[1,2] * m[2,0]
		
		MOV RESULTADOS[1*2], AX
		
		;TERCERA MULTIPLICACION QUE SUMA
		MOV AX, MATRIZ[2*2]
		MOV DX, MATRIZ[3*2]
		IMUL DX                    	;AX = m[1,0] * m[2,1]
		MOV DX, MATRIZ[7*2]
		IMUL DX 					;AX = m[1,0] * m[2,1] * m[0,2]
		
		MOV RESULTADOS[2*2], AX
		
		
		;PRIMERA MULTIPLICACION QUE RESTA
		MOV AX, MATRIZ[2*2]
		MOV DX, MATRIZ[4*2]
		IMUL DX                    	;AX = m[0,2] * m[1,1]
		MOV DX, MATRIZ[6*2]
		IMUL DX 					;AX = m[0,2] * m[1,1] * m[2,0]
		
		MOV RESULTADOS[3*2], AX
		
		;SEGUNDA MULTIPLICACION QUE RESTA
		MOV AX, MATRIZ[5*2]
		MOV DX, MATRIZ[7*2]
		IMUL DX                    	;AX = m[1,2] * m[2,1]
		MOV DX, MATRIZ[0]
		IMUL DX 					;AX = m[1,2] * m[2,1] * m[0,0]
		
		MOV RESULTADOS[4*2], AX
		
		;TERCERA MULTIPLICACION QUE RESTA
		MOV AX, MATRIZ[1*2]
		MOV DX, MATRIZ[3*2]
		IMUL DX                     ;AX = m[0,1] * m[1,0]
		MOV DX, MATRIZ[8*2]
		IMUL DX 					;AX = m[0,1] * m[1,0] * m[2,2]
		
		MOV RESULTADOS[5*2], AX
		
		;AHORA HACEMOS LOS CALCULOS
		MOV AX, RESULTADOS[0*2]
		ADD AX, RESULTADOS[1*2]
		ADD AX, RESULTADOS[2*2]
		SUB AX, RESULTADOS[3*2]
		SUB AX, RESULTADOS[4*2]
		SUB AX, RESULTADOS[5*2]
		
		MOV BX, AX
		RET
	DETERMINANTE ENDP 

	;_______________________________________________________________ 
	; SUBRUTINA PARA CALCULAR CUANDO SE INTRODUCE UN SOLO NUMERO 
	; NO DEVUELVE NADA
	;_______________________________________________________________ 
	TECLADO1 PROC NEAR 
		MOV AL, AUX[2]
		MOV AUX[4], AL
		MOV AL, 30H 
		MOV AUX[2], AL
		MOV AUX[3],AL
		
		RET
	TECLADO1 ENDP 

	;_______________________________________________________________ 
	; SUBRUTINA PARA CALCULAR CUANDO SE INTRODUCEN SOLO DOS NUMEROS 
	; NO DEVUELVE NADA
	;_______________________________________________________________ 
	TECLADO2 PROC NEAR 
		MOV AL, AUX[2]
		MOV AH, AUX[3]
		MOV AUX[3], AL
		MOV AUX[4], AH
		MOV AL, 30H 
		MOV AUX[2], AL
		
		RET
	TECLADO2 ENDP 

	;_______________________________________________________________ 
	; SUBRUTINA PARA CONVERTIR EL NUMERO LEIDO EN ASCII A NUMERO NORMAL EN DECIMAL 
	; SALIDA BX=NUMERO CONVERTIDO
	;_______________________________________________________________
	CONVERTIRNUMERO PROC NEAR
		MOV AL, AUX[2]
		MOV AH, 0
		MOV DX, 48 
		SUB AX,DX
		MOV DX, 100
		IMUL DX
		MOV BX,AX ;BX CONTIENE LAS CENTENAS
		
		;LUEGO LAS DECENAS
		MOV AL, AUX[3]
		MOV AH, 0
		MOV DX, 48
		SUB AX,DX
		MOV DX, 10
		IMUL DX
		ADD AX,BX
		MOV BX, AX ;BX CONTIENE LAS DECENAS Y CENTENAS
		
		;TERMINAMOS CON LAS UNIDADES
		MOV AL, AUX[4]
		MOV AH, 0
		MOV DX, 48
		SUB AX,DX
		ADD AX,BX
		MOV BX, AX ;BX CONTIENE EL NUMERO BIEN
		
		RET
	CONVERTIRNUMERO ENDP

	;_______________________________________________________________ 
	; SUBRUTINA PARA CONVERTIR NUMEROS NEGATIVOS DE DOS CIFRAS 
	; SALIDA BX=NUMERO CONVERTIDO
	;_______________________________________________________________
	MENOS2 PROC NEAR
		;PRIMERO LAS DECENAS
		MOV AL, AUX[3]
		MOV AH, 0
		MOV DX, 48
		SUB AX,DX
		MOV DX, 10
		IMUL DX
		MOV BX, AX ;BX CONTIENE LAS DECENAS
		
		;TERMINAMOS CON LAS UNIDADES
		MOV AL, AUX[4]
		MOV AH, 0
		MOV DX, 48
		SUB AX,DX
		ADD AX,BX
		MOV BX, AX ;BX CONTIENE EL NUMERO BIEN
		
		MOV AX,0
		SUB AX,BX
		MOV BX, AX
		
		RET
	MENOS2 ENDP

	;_______________________________________________________________ 
	; SUBRUTINA PARA CONVERTIR NUMEROS NEGATIVOS DE UNA CIFRA
	; SALIDA BX=NUMERO CONVERTIDO
	;_______________________________________________________________
	MENOS1 PROC NEAR
		;SOLO LAS UNIDADES
		MOV AL, AUX[4]
		MOV AH, 0
		MOV DX, 48
		SUB AX,DX
		MOV BX, AX ;BX CONTIENE EL NUMERO BIEN
		
		MOV AX,0
		SUB AX,BX
		MOV BX, AX
		
		RET
	MENOS1 ENDP
CODE ENDS 
; FIN DEL PROGRAMA INDICANDO DONDE COMIENZA LA EJECUCION 
END START 

