all: help

help:
	@echo "Este es el Makefile de la P2 de Alba Ramos y Nicolás Serrano"
	@echo "Los comandos disponibles son:"
	@echo "ayuda_retro, compilar, ejecuta_problema_real2, ejecuta_problema_real6"

ayuda_retro:
	python3 main.py -ayuda_retro

compilar:
	python3 main.py -compilar

ejecuta_problema_real2:
	python3 main.py -ejecuta_problema_real2

ejecuta_problema_real6:
	python3 main.py -ejecuta_problema_real6